"""LangGraph State Definition for Travel Policy Agent.

This module defines the shared state passed between nodes in the StateGraph.
In LangGraph, the State acts as the single source of truth for the workflow.
Each node receives this state, performs its computation, and returns a dictionary
of state updates.
"""

from typing import List, Dict, Any, Optional
from typing_extensions import TypedDict
from langchain_core.documents import Document


class AgentState(TypedDict):
    """The central state structure for the Travel Policy LangGraph workflow.
    
    Attributes:
        original_question: The unmodified question provided by the user.
        rewritten_question: An optimized version of the query generated by the
            query rewriter node to maximize retrieval performance.
        retrieved_docs: List of Document objects returned by the retriever.
        context_text: Formatted string representation of the retrieved document chunks.
        is_context_relevant: Boolean flag indicating if context passed relevance validation.
        answer: The synthesized answer generated from the context.
        is_answer_grounded: Boolean flag indicating if the answer passed hallucination/grounding checks.
        evaluation_feedback: Feedback explanation if the answer or context needs revision.
        retry_count: Current number of retry attempts executed in the graph loop.
        max_retries: Maximum allowable revision/retry iterations before falling back.
        trace_logs: List of human-readable diagnostic messages tracking node executions.
    """
    original_question: str
    rewritten_question: str
    retrieved_docs: List[Document]
    context_text: str
    is_context_relevant: bool
    answer: str
    is_answer_grounded: bool
    evaluation_feedback: str
    retry_count: int
    max_retries: int
    trace_logs: List[str]
